load("@buck2-haskell//:defs.bzl", "haskell_library")

extensions = [
]

ghc_flags = ["-X" + ext for ext in extensions] + [
    "-Wall",
    "-fwarn-incomplete-uni-patterns",
    "-fwarn-incomplete-record-updates",
    "-funbox-strict-fields",
]

haskell_library(
    name = "amazonka-kinesisanalyticsv2",
    srcs = glob([
        "src/**/*.hs",
        "src/**/*.hs-boot",
        "gen/**/*.hs",
        "gen/**/*.hs-boot",
    ]),
    compiler_flags = ghc_flags,
    strip_prefix = [
        "gen",
        "src",
    ],
    visibility = ["//amazonka/..."],
    deps = [
        "//amazonka/lib/amazonka-core",
        "//haskell:base",
    ],
)
