load("@buck2-haskell//:defs.bzl", "haskell_library")

extensions = [
    "NoImplicitPrelude",
    "DataKinds",
    "DeriveAnyClass",
    "DeriveFoldable",
    "DeriveFunctor",
    "DeriveGeneric",
    "DeriveTraversable",
    "DerivingStrategies",
    "DerivingVia",
    "FlexibleContexts",
    "FlexibleInstances",
    "GeneralizedNewtypeDeriving",
    "LambdaCase",
    "NamedFieldPuns",
    "OverloadedStrings",
    "PatternSynonyms",
    "RankNTypes",
    "RecordWildCards",
    "ScopedTypeVariables",
    "StrictData",
    "TupleSections",
    "TypeApplications",
    "TypeFamilies",
    "ViewPatterns",
]

ghc_flags = ["-X" + ext for ext in extensions] + [
    "-Wall",
    "-funbox-strict-fields",
    "-fwarn-incomplete-uni-patterns",
    "-fwarn-incomplete-record-updates",
    "-fwarn-missing-deriving-strategies",
    "-fwarn-unused-packages",
]

haskell_library(
    name = "amazonka-s3-encryption",
    srcs = glob([
        "src/**/*.hs",
        "src/**/*.hs-boot",
    ]),
    compiler_flags = ghc_flags,
    strip_prefix = [
        "gen",
        "src",
    ],
    visibility = ["//amazonka/..."],
    deps = [
        "//amazonka/lib/amazonka",
        "//amazonka/lib/amazonka-core",
        "//amazonka/lib/services/amazonka-kms",
        "//amazonka/lib/services/amazonka-s3",
        "//haskell:aeson",
        "//haskell:base",
        "//haskell:bytestring",
        "//haskell:case-insensitive",
        "//haskell:conduit",
        "//haskell:crypton",
        "//haskell:http-client",
        "//haskell:lens",
        "//haskell:memory",
        "//haskell:mtl",
        "//haskell:text",
        "//haskell:unordered-containers",
    ],
)
